name: PR

on:
  pull_request:
    branches: [ "main", "hack" ]

jobs:

  build:
    permissions:
      contents: read  # This is required for actions/checkout
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.3'

    - uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: Build
      run: make build

#    TODO: uncomment once we add code
#    - name: golangci-lint
#      uses: golangci/golangci-lint-action@v7
#      with:
#        version: v2.1.5

    - name: Test
      run: make test
